### ISSUE TITLE
bug(vtz): missing vm module breaks happy-dom — 7 packages fail

### ISSUE THREAD

**Issue by viniciusdacal** [vertz-dev/vertz#2631]
## Description

The vtz runtime doesn't provide the `vm` built-in Node.js module. happy-dom requires it for `Window` initialization, causing load errors across all packages that use happy-dom for testing.

```
Error: Cannot find module 'vm' in node_modules
(searched from .../happy-dom/lib/window)
```

## Affected packages (7)

- `@vertz/icons` — render-icon.test.ts
- `@vertz/ui-canvas` — all canvas tests
- `@vertz/ui-auth` — access-gate, auth-gate, avatar tests
- `@vertz/docs` — api-components, breadcrumbs, build-pipeline, compile-mdx-html, mdx-components
- `@vertz/ui` — provider-icons.test.ts (partial — other ui failures have additional causes)
- `@vertz/theme-shadcn` — app-shell, configure, globals, merge tests
- `@vertz/create-vertz-app` — template tests (via transitive happy-dom dep)

## Previous issue

#2605 was created for this but was closed. The failure persists on CI (run 24402636517).

## Acceptance Criteria

- [ ] `vm` module (at minimum `vm.createContext`, `vm.runInContext`, `vm.Script`) available in vtz runtime
- [ ] happy-dom tests pass under `vtz test`

**Comment by viniciusdacal** [comment]
Closing — the root cause is addressed by merged PRs:

- **PR #2614** added the `vm` module to the ESM resolution layer in `native/vtz/src/runtime/module_loader.rs`, including `isContext()` support. This fixes the happy-dom `Cannot find module 'vm'` error that was the root cause for all 7 affected packages.
- **PR #2621** separately fixed `@vertz/theme-shadcn` test failures (app-shell, primitive-styles, styles).
- **PR #2604** fixed `@vertz/ui` test failures (10 files, 292 tests).
- **PR #2613** fixed `@vertz/ui-primitives` composed component test failures.

The remaining packages (`@vertz/icons`, `@vertz/ui-canvas`, `@vertz/ui-auth`, `@vertz/docs`, `@vertz/create-vertz-app`) all fail due to the same missing `vm` module — with #2614 merged, happy-dom should resolve correctly.

If any of these packages still fail with `vm`-related errors after these merges, please reopen.
