### ISSUE TITLE
fix(e2e): runtime error overlay test broken after createRouter auto-detect (#1219)

### ISSUE THREAD

**Issue by viniciusdacal** [vertz-dev/vertz#1223]
## Description

The runtime error overlay E2E test in the task-manager example fails after #1219 (`createRouter` auto-detect initialPath).

**Test:** `examples/task-manager/e2e/runtime-error-overlay.spec.ts`

**What happens:**
1. Test injects a broken component (`NonExistentComponent.render()`) into `task-card.tsx`
2. HMR triggers SSR re-render
3. SSR re-render hits `window.addEventListener is not a function` because the router's popstate listener runs in SSR context
4. Error overlay shows the SSR error instead of the expected `NonExistentComponent` runtime error

**Expected:** Overlay shows `NonExistentComponent` reference error with source file path
**Actual:** Overlay shows `SSR error` + `window.addEventListener is not a function`

**Root cause:** `createRouter(routes, { serverNav: true })` auto-detects the environment. When SSR re-renders after HMR, the router module is re-evaluated in SSR context where `window` doesn't exist. The `isBrowser()` guard likely doesn't cover the popstate listener setup path, or the SSR re-import doesn't properly set up the non-browser code path.

**Introduced in:** PR #1219 (auto-detect initialPath)
**Affects:** task-manager E2E only — unit/integration tests all pass

## Acceptance Criteria

- [ ] `runtime-error-overlay.spec.ts` passes: overlay contains `NonExistentComponent` and `src/components/task-card.tsx`
- [ ] `createRouter` SSR path does not attempt to access `window.addEventListener`
- [ ] All other E2E tests continue to pass
